config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/", to: "pages#home_search"

  get "profile", to: "pages#profile", as: 'profile'

  get "/search", to: "pages#render_location_partial", as: :location_partial
  get "/search/delete", to: "pages#render_empty_location_partial", as: :empty_loacation_partial

  get "/api/autocomplete", to: "api#fetch_autocomplete_data", as: :fetch_autocomplete_data

  post "/matches/:id/finish", to: "matches#finish", as: :finish_match
  post "/matches/:id/end", to: "matches#end", as: :end_match

  get "/profile/:id/new_guide", to: "pages#new_guide", as: :new_guide
  put "/profile/:id/create_guide", to: "pages#apply_guide", as: :apply_guide

  resources :locations, only: [:create, :destroy]

  resources :users, only: [:index, :show]

  resources :matches, only: [:new, :create, :destroy]



  resources :matches, only: [:index, :show, :new, :update] do
    resources :reviews, only: [:new, :create]
    resources :messages, only: [:create]
  end

  post "/profile/add_interest", to: "pages#add_interest", as: :add_interest
  delete "/profile/remove_interest", to: "pages#remove_interest", as: :remove_interest

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :user_interests, dependent: :destroy
  has_many :interests, through: :user_interests

  has_many :guide_locations, dependent: :destroy
  has_many :locations, through: :guide_locations

  has_many :guide_matches, class_name: 'Match', foreign_key: 'guide_id', dependent: :destroy
  has_many :tourist_matches, class_name: 'Match', foreign_key: 'tourist_id', dependent: :destroy

  has_many :guides, through: :tourist_matches, class_name: 'User', foreign_key: 'guide_id'
  has_many :tourists, through: :guide_matches, class_name: 'User', foreign_key: 'tourist_id'

  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true
  validates :password, presence: true, unless: -> { password.blank? }
  validates :guide_description, presence: true, if: :guide?

  def users_with_shared_interests
    User.joins(:user_interests)
        .where(user_interests: { interest_id: self.interest_ids })
        .where.not(id: self.id)
        .select("users.*, COUNT(user_interests.interest_id) AS shared_interests_count")
        .group("users.id")
        .order("shared_interests_count DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @guides = User.where(guide: true)
  end

  def show
    @this_match = Match.where(tourist_id: current_user.id, guide_id: params[:id])
    @guide = User.find(params[:id])
    @guide_interests = @guide.interests.pluck(:interest)
    @user = current_user
    @user_interests = @user.interests.pluck(:interest)
    @match = Match.new

    @reviews = Review.joins(:match).where(matches: { guide_id: @guide.id })
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add/update photo" %>
<% end %>

app/views/users/index.html.erb
<div class="align-items-center text-center mt-2 basic-padding">

  <h1>All users</h1>
    <% @users.each do |user| %>
    <div class="d-flex border w-100 mt-4 rounded" style="height: 100px;">
      <%= image_tag 'profile-picture.webp', alt: 'guide' %>
      <div class="justify-content-start text-start ms-2 mt-1">
        <h2><%= link_to user.name, user_path(user) %></h2>
        <p><%= user.short_description %></p>
      </div>
    </div>
    <% end %>
    
    <br>
    <br>
    <h1>Guides</h1>
    <% @guides.each do |guide| %>
    <div class="d-flex border w-100 mt-4 rounded" style="height: 100px;">
      <%= image_tag 'profile-picture.webp', alt: 'guide' %>
      <div class="justify-content-start text-start ms-2 mt-1">
        <h2><%= link_to guide.name, user_path(guide) %></h2>
        <p><%= guide.short_description %></p>
      </div>
    </div>
    <% end %>

</div>

app/views/users/show.html.erb
<% location = params[:location] %>

<div class="basic-padding user-details mt-2">
  <h1 class="user-name"><%= @guide.name %></h1>
  <p class="user-show-description"><%= @guide.guide_description %></p>
</div>

<div class="text-center main-photo">
  <% if @guide.photo.key != nil %>
    <%= cl_image_tag(@guide.photo.key, height: 250, width: 372, gravity: "faces", crop: "fill", class: "cloudinary-image") %>
    <%#= image_tag(profile_image, alt: 'profile picture') %>
    <%#= cl_image_tag(@guide.photo.key, crop: "scale", transformation: [gravity: "face"]) %>
  <% end %>
</div>

<div class="basic-padding">
  <% if @guide == current_user %>
    <p><%= link_to "Edit profile", edit_user_registration_path(current_user), class: 'btn btn-connect' %></p>
  <% elsif (match = @this_match[0]) %>
    <% if match.status == 'accepted' %>
      <p class='status-message'><img src="<%= asset_path('Chain.png') %>" class="chain-emoji"/>Status: accepted</p>
      <%= button_to("Chat", match_path(match), class: 'btn-connect', method: :get) %>
    <% elsif match.status == 'pending' %>
      <p class='status-message'><img src="<%= asset_path('Chain.png') %>" class="chain-emoji"/>Status: waiting for guide to accept...</p>
    <% elsif match.status == 'declined' %>
      <p class='status-message'>Your connection request was declined. You cannot send a request to this guide anymore.</p>
    <% elsif match.status == 'finished' %>
      <p class='status-message'><img src="<%= asset_path('Chain.png') %>" class="chain-emoji"/>Status: finished</p>
    <% elsif match.status == 'cancelled' %>
      <p class='status-message'><img src="<%= asset_path('Chain.png') %>" class="chain-emoji"/>Status: cancelled</p>
    <% elsif match.status == 'finishing'  %>
      <p class='status-message'><img src="<%= asset_path('Chain.png') %>" class="chain-emoji"/>Status: waiting for guide to close the connection...</p>
    <% else %>
      <p>Unknown status</p>
    <% end %>
  <% else %>
    <%= link_to "Connect!", new_match_path(location_id: location, guide_id: @guide.id), class: 'btn btn-connect' %>
  <% end %>


  <div class="show-page-border"></div>

    <p class="text-center fs-5 mb-4"><strong>Interests 🤩</strong></p>
    <% sorted_interests = @guide_interests.sort_by { |interest| @user_interests.include?(interest) ? 0 : 1 } %>
      <div class="interests-container mb-3 interests-container-guide">
        <% sorted_interests.each do |interest| %>
          <% if @user_interests.include?(interest) %>
            <div class="interest-guide-common">
              <%= interest %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="interest-border"></div>

      <div class="interests-container interests-container-guide">
        <% sorted_interests.each do |interest| %>
          <% unless @user_interests.include?(interest) %>
            <div class="interest-guide">
              <%= interest %>
            </div>
          <% end %>
        <% end %>
      </div>

  <div class="show-page-border"></div>

    <p class="text-center fs-5 mb-4"><strong>Locations 📍</strong></p>
    <% @grouped_locations = @guide.locations.group_by(&:country) %>
    <% @grouped_locations_alf = @grouped_locations.keys.sort %>
    <% @grouped_locations_alf.each do |country| %>
      <% @grouped_locations[country].sort_by(&:city).each do |location| %>
        <p class="text-center fs-6"> <%= country_to_flag(country) %> <%= location.name %>, <%= location.city %> </p>
      <% end %>
    <% end %>

  <div class="show-page-border"></div>

    <p class="text-center fs-5 mb-4"><strong>Reviews ⭐️</strong></p>
    <div class="d-flex flex-column review-container">
      <% if @reviews.empty? %>
        <p class="text-center"><%= @guide.name %> has no reviews yet...</p>
      <% else %>
        <% @reviews.each do |review| %>
          <p class="review-content">"<%= review.content %>"</p>
          <p class="review-details"><i>Written by <%= review.user.name %> on <%= review.created_at.strftime("%d-%m-%Y") %></i></p>
          <div class="review-border"></div>
        <% end %>
      <% end %>
      <br>
  </div>
</div>