config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/", to: "pages#home_search"

  get "profile", to: "pages#profile", as: 'profile'

  get "/search", to: "pages#render_location_partial", as: :location_partial
  get "/search/delete", to: "pages#render_empty_location_partial", as: :empty_loacation_partial

  get "/api/autocomplete", to: "api#fetch_autocomplete_data", as: :fetch_autocomplete_data

  post "/matches/:id/finish", to: "matches#finish", as: :finish_match
  post "/matches/:id/end", to: "matches#end", as: :end_match

  get "/profile/:id/new_guide", to: "pages#new_guide", as: :new_guide
  put "/profile/:id/create_guide", to: "pages#apply_guide", as: :apply_guide

  resources :locations, only: [:create, :destroy]

  resources :users, only: [:index, :show]

  resources :matches, only: [:new, :create, :destroy]



  resources :matches, only: [:index, :show, :new, :update] do
    resources :reviews, only: [:new, :create]
    resources :messages, only: [:create]
  end

  post "/profile/add_interest", to: "pages#add_interest", as: :add_interest
  delete "/profile/remove_interest", to: "pages#remove_interest", as: :remove_interest

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/shared/_flashes.html.erb
<section id="flashes">
  <% if notice %>
    <div data-controller="flash" data-flash-timeout-value="3000" class="flash flash-warning alert alert-dismissible show" role="alert">
      <span><%= notice %></span>
      <a data-bs-dismiss="alert" aria-label="Close" class="ms-2">
        <i class="fas fa-times"></i>
      </a>
    </div>
  <% end %>
  <% if alert %>
    <div data-controller="flash" data-flash-timeout-value="3000" class="flash flash-danger alert alert-dismissible show" role="alert">
      <span><%= alert %></span>
      <a data-bs-dismiss="alert" aria-label="Close" class="ms-2">
        <i class="fas fa-times"></i>
      </a>
    </div>
  <% end %>
</section>

app/views/shared/_footer.html.erb
<div data-controller="search-form">
  <%= render "shared/search_form_main" %>
  <div class="footer">
    <div class="footer-icons d-flex justify-content-around align-items-center pt-2 footer-container">
      <%= link_to matches_path, class: "text-grey text-center" do %>
        <i class="fa fa-users fa-2x"></i>
      <% end %>

      <div class="search-option">
          <i class="fa fa-search text-grey text-center" data-action="click->search-form#showSearchForm:prevent"></i>
      </div>

      <%= link_to profile_path, class: "text-grey text-center" do %>
        <i class="fa fa-user fa-2x"></i>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="main-header" id="header" >
    <a href="/"><img src="<%= asset_path('TripLink.png') %>" alt="Logo" class="logo"></a>
    <!-- check if one of the guide_matches from the user has the status pending -->


        <% if user.guide_matches.any? { |match| match.status == "pending" } %>

          <% pending_match_count = user.guide_matches.where(status: 'pending').count %>

          <a href="matches" class="bell active">
            <span class="pending-match-count"><%= pending_match_count %></span>
            <i class="fa-solid fa-bell"></i>
          </a>

        <% else %>
          <i id="dynamicBell" class="fa-solid fa-bell bell <%= added_class %>"></i>
        <% end %>
</header>

app/views/shared/_header_logged_out.html.erb
<section data-controller="intromodal">

  <header class="main-header" id="header">
    <a href="/"><img src="<%= asset_path('TripLink.png') %>" alt="Logo" class="logo"></a>

    <i data-action="click->intromodal#show" class="fa-solid fa-question bell active"></i>
  </header>


  <div class="intromodal d-none" data-intromodal-target="canvas">
    <div class="modal-content">
    <span class="close" data-action="click->intromodal#close">&times;</span>
    <h1>Welcome to TripLink!</h1>
    <h2>Looking for an authentic travel experience?</h2> <h3> TripLink connects you with local guides who know the area, helping you discover hidden gems and unique stories for an unforgettable trip!</h3>
    <h3>We’re Valentijn, Timo, and Denise, students from Le Wagon, and we’re excited to share this unique journey with you.</h3>
    </div>
  </div>
</section>

app/views/shared/_search_form_main.html.erb
<div class="search-form-wrapper d-none" data-search-form-target="bar">
  <form action="/" method="post" autocomplete="off">
    <div class="search-form row">
      <input type="text" data-search-form-target="input" data-action="input->search-form#fetchSearchResults:prevent" class="search-form-input col-10" name="location_search" placeholder="Search for a location" />
      <input type="hidden" data-search-form-target="city" name="city" />
      <input type="submit" class="search-form-submit col-2" name="submit" value="→" />
    </div>
  </form>
  <div class="autocomplete-wrapper">
    <ul class="list-group" data-search-form-target="results">
      <!-- here list items will be inserted by the stimulus controller search_from_controller.js -->
    </ul>
  </div>
</div>