config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/", to: "pages#home_search"

  get "profile", to: "pages#profile", as: 'profile'

  get "/search", to: "pages#render_location_partial", as: :location_partial
  get "/search/delete", to: "pages#render_empty_location_partial", as: :empty_loacation_partial

  get "/api/autocomplete", to: "api#fetch_autocomplete_data", as: :fetch_autocomplete_data

  post "/matches/:id/finish", to: "matches#finish", as: :finish_match
  post "/matches/:id/end", to: "matches#end", as: :end_match

  get "/profile/:id/new_guide", to: "pages#new_guide", as: :new_guide
  put "/profile/:id/create_guide", to: "pages#apply_guide", as: :apply_guide

  resources :locations, only: [:create, :destroy]

  resources :users, only: [:index, :show]

  resources :matches, only: [:new, :create, :destroy]



  resources :matches, only: [:index, :show, :new, :update] do
    resources :reviews, only: [:new, :create]
    resources :messages, only: [:create]
  end

  post "/profile/add_interest", to: "pages#add_interest", as: :add_interest
  delete "/profile/remove_interest", to: "pages#remove_interest", as: :remove_interest

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/views/pages/_location_information_window.html.erb
<div id="location-info">
  <% if location == nil %>
  <% else %>

    <div class="location-info-wrapper" data-controller="map-partial">
      <div class="partial-top-bar">
        <span data-action="click->map-partial#close" class="close">close</span>
      </div>
      <div class="location-info-container">
        <% if defined?(location) %>
          <div class="location-heading">
            <h1><%= location.city %>, <%= location.country %> <%= country_to_flag(location.country) %></h1>
            <div class="location-divider"></div>
          </div>
        <% end %>

        <!-- if user is not signed in show the login button -->
        <% if defined?(guides) && guides.any? %>
          <h1 class="guides-heading">Guides</h1>
          <% if !user_signed_in? %>
            <p> Sign in or sign up to connect with a guide </p>
            <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary mb-2", data: { turbo: false } %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary mb-2", data: { turbo: false } %>
          <% else %>
            <div class="guides-container text-center">
              <% guides.each do |guide| %>
                <%= link_to user_path(guide, location: location.id), data: { turbo: false }, class: "guide-card-link" do %>
                  <div class="guide-card">
                    <% if guide.photo.key.present? %>
                      <%= cl_image_tag(guide.photo.key, width: 150, height: 150, crop: "fill", gravity: "face") %>
                    <% else %>
                      <%= image_tag 'profile-picture.webp', class: "guide-card-image", alt: 'guide' %>
                    <% end %>
                    <div class="guide-card-content">
                      <h2 class="guide-card-title"><%= guide.name %></h2>
                      <p class="guide-card-description"><%= guide.short_description %></p>
                      <div class="guide-card-locations">
                        <% locations = guide.locations.where(city: location.city).limit(3) %>
                        <% if locations.any? %>
                          <p>
                            <% locations.each do |loc| %>
                              📍 <%= loc.name %><br>
                            <% end %>
                          </p>
                        <% else %>
                          <p>No locations available in <%= location.city %> for this guide.</p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <h2 class="mt-5">No guides available</h2>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%# this is the map on the homepage %>
<div  style="width: 100vw; height: 100dvh;"
      class="map-canvas"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<%= turbo_frame_tag :location_details do %>
  <%= render "location_information_window", location: nil, guides: nil %>
<% end %>

app/views/pages/new_guide.html.erb
<div class="basic-padding">

  <h2>Apply to be a guide</h2>

  <%= simple_form_for(@user, url: apply_guide_path(@user), html: { method: :put }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

        <!-- guide description & rate input field -->
        <%= f.input :guide_description, required: true %>

      <%= f.input :current_password,
                  required: false,
                  input_html: { autocomplete: "current-password" } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Apply", class: "btn btn-primary" %>
      <%= link_to "Back", :back, class: "btn btn-outline-primary" %>
    </div>
  <% end %>

</div>

app/views/pages/profile.html.erb
<div class="basic-padding">

  <!-- if user is not signed in, show the login button -->
  <% if !user_signed_in? %>
      <p> <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary" %></p>

  <!-- if user is signed in, show the profile page -->
  <% else %>

    <div class="profile-page-border"></div>

    <div class="d-flex justify-content-between">
      <div class="d-flex align-items-center">
        <% if @user.photo.key != nil %>
          <%= cl_image_tag(@user.photo.key, height: 75, width: 75, gravity: "faces", crop: "fill", class: "rounded-circle") %>
        <% end %>
        <h1 class="ms-3"> <%= @user.name%> </h1>
      </div>
      <div class="d-flex align-items-center">
        <% if @user.guide == false || @user.guide == nil %>
          <%= button_to "Apply to be a guide", new_guide_path(@user), method: :get, class: "btn btn-outline-primary mb-2" %>
        <% end %>
      </div>
    </div>

    <div class="profile-page-border"></div>

    <h2 class="mb-3">Your interests</h2>
    <div class="interests-container interests-container-profile">
      <% @user.interests.sort_by(&:interest).each do |interest| %>
          <div class="interest-profile align-items-center">
          <span class="me-2"><%= interest.interest %></span>
          <%= button_to 'ⓧ', remove_interest_path(interest_id: interest.id), method: :delete, class: 'btn-delete background-white' %>
        </div>
      <% end %>
    </div>
    <% if @available_interests.any? %>
      <%= form_with url: add_interest_path, method: :post do |f| %>
      <p class="mt-3">Want to add an interest to your profile?</p>
      <div class="input-button-group">
        <%= f.collection_select :interest_id, @available_interests.sort_by(&:interest), :id, :interest, { prompt: "Select interest"}, class: 'input-field' %>
        <%= f.submit "Add", class: "submit-button add-button" %>
      </div>
      <% end %>
    <% end %>

    <div class="profile-page-border"></div>

      <% if @user.guide == true %>

        <section class="d-flex justify-content-between align-items-center">
          <h2>Your guide locations</h2>

          <section data-controller="new-location">

            <button class="submit-button add-button ms-2 d-flex" data-action="new-location#show:prevent">Add +</button>
            <div class="intromodal d-none" data-new-location-target="canvas">
              <div class="modal-content">
                <span class="close" data-action="click->new-location#close:stop">&times;</span>
                <h1>New location</h1>

                  <%= simple_form_for @location do |f| %>
                    <%= f.input :address, placeholder: "Type address...", label: false, class: "new-location-search", input_html: { data: { action: "input->new-location#fetchSearchResults", new_location_target: "input" }, autocomplete: "off" } %>
                  <div class="autocomplete-wrapper new-location-autocomplete">
                    <ul class="list-group" data-new-location-target="results">
                      <!-- here list items will be inserted by the stimulus controller search_from_controller.js -->
                    </ul>
                  </div>
                    <%= f.input :name, placeholder: "Name your location...", label: false, input_html: { data: { new_location_target: "name" } } %>
                    <%= f.hidden_field :full_address, value: "", data: { new_location_target: "address" } %>
                    <%= f.button :submit, value: "add location", class: 'btn btn-primary'%>
                  <% end %>

              </div>
            </div>
          </section>

        </section>

        <ul class="list-group mt-3">
          <% @user.locations.each do |location| %>
            <li class="list-group-item d-flex justify-content-start">
            <%= button_to 'ⓧ', location_path(location.id, current_user.id), class: "btn-delete mt-1 me-2 background-light-gray", method: :delete %>
            <span class="ms-2"><%= location.name %>, <%= location.city %></span>
            </li>
          <% end %>
        </ul>
      <% end %>

      <div class="d-flex justify-content-end">
        <div class="d-flex justify-content-start mt-4">
          <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-outline-primary ms-2" %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-warning ms-2" %>
        </div>
      </div>
      <br>

  <% end %>
</div>