config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/", to: "pages#home_search"

  get "profile", to: "pages#profile", as: 'profile'

  get "/search", to: "pages#render_location_partial", as: :location_partial
  get "/search/delete", to: "pages#render_empty_location_partial", as: :empty_loacation_partial

  get "/api/autocomplete", to: "api#fetch_autocomplete_data", as: :fetch_autocomplete_data

  post "/matches/:id/finish", to: "matches#finish", as: :finish_match
  post "/matches/:id/end", to: "matches#end", as: :end_match

  get "/profile/:id/new_guide", to: "pages#new_guide", as: :new_guide
  put "/profile/:id/create_guide", to: "pages#apply_guide", as: :apply_guide

  resources :locations, only: [:create, :destroy]

  resources :users, only: [:index, :show]

  resources :matches, only: [:new, :create, :destroy]



  resources :matches, only: [:index, :show, :new, :update] do
    resources :reviews, only: [:new, :create]
    resources :messages, only: [:create]
  end

  post "/profile/add_interest", to: "pages#add_interest", as: :add_interest
  delete "/profile/remove_interest", to: "pages#remove_interest", as: :remove_interest

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :guide, class_name: 'User', foreign_key: 'guide_id'
  belongs_to :tourist, class_name: 'User', foreign_key: 'tourist_id'

  belongs_to :location

  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validate :guide_is_valid
  validates :tourist, :location, :status, presence: true

  validates :status, inclusion: { in: %w(pending accepted finishing finished declined cancelled) }

  after_create :broadcast_guide_notification
  # commented this line to prevent the function from being triggered immediately
  # after_create :broadcast_guide_match

  def broadcast_guide_match
      broadcast_prepend_to "incomming_matches-#{guide.id}",
                          partial: "matches/guide_match",
                          target: "incomming_matches",
                          locals: { match: self, incoming: "New request" }

      broadcast_replace_to "incomming_matches-#{guide.id}",
                          partial: "matches/guide_match",
                          target: "match_#{id}",
                          locals: { match: self, incoming: "New request" }
  end

  def broadcast_update_guide_match
    broadcast_replace_to "incomming_matches-#{guide.id}",
                          partial: "matches/guide_match",
                          target: "match_#{id}",
                          locals: { match: self, incoming: false }
  end

  def broadcast_tourist_match
      broadcast_replace_to "incomming_matches-#{tourist.id}",
                          partial: "matches/tourist_match",
                          target: "match_#{id}",
                          locals: { match: self }
  end

  def broadcast_guide_notification(text = "You have a new connection request!")
    broadcast_replace_to "flashes-#{guide.id}",
                        partial: "shared/flashes",
                        target: "flashes",
                        locals: { notice: text, alert: false }

    broadcast_replace_to "header-#{guide.id}",
                        partial: "shared/header",
                        target: "header",
                        locals: { added_class: "active", user: guide }
  end

  private

  def guide_is_valid
    if guide.present? && !guide.guide?
      errors.add(:guide, "guide must be a user with guide set to true")
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_guide, only: [:new]
  before_action :set_match, only: [:show, :create_message]

  def index
    @user = current_user
    @matches_as_tourist = Match.where(tourist_id: @user)
    @matches_as_guide = Match.where(guide_id: @user)
  end

  def update
    @match = Match.find(params[:id])
    @match.status = params[:status]
    if @match.save
      @match.broadcast_tourist_match
      redirect_to matches_path
    else
      render :show
    end
  end

  def finish
    @match = Match.find(params[:id])
    @match.status = "finishing"
    if @match.save
      @match.broadcast_guide_notification(@match.tourist.name + " wants to finish your connection")
      @match.broadcast_update_guide_match
      redirect_to matches_path, notice: "finish connection request sent"
    else
      redirect_to matches_path, alert: "Failed to finish connection"
    end
  end

  def end
    @match = Match.find(params[:id])
    if params[:value] == "yes"
      @match.status = "finished"
      if @match.save
        redirect_to matches_path, notice: "Connection finished"
      else
        redirect_to matches_path, alert: "Failed to finish connection"
      end
    elsif params[:value] == "no"
      @match.status = "accepted"
      if @match.save
        redirect_to matches_path, notice: "Connection resumed"
      else
        redirect_to matches_path, alert: "Failed to finish connection"
      end
    elsif params[:value] == "cancel"
      @match.status = "cancelled"
      if @match.save
        redirect_to matches_path, notice: "Connection cancelled"
      else
        redirect_to matches_path, alert: "Failed to cancel connection"
      end
    end
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new

    if current_user == @match.tourist
      @matched_user = @match.guide
    else
      @matched_user = @match.tourist
    end
  end

    def new
      @guide = User.find(params[:guide_id])
      @match = Match.new
    end

  def create
    if params[:match][:message] == ""
      redirect_to new_match_path(location_id: params[:match][:location_id], guide_id: params[:match][:guide_id]), alert: "Message can't be blank"
    else
      @match = Match.new
      @match.tourist = current_user
      @match.guide = User.find(params[:match][:guide_id])
      @match.location = Location.find(params[:match][:location_id])
      @match.status = "pending"


      if @match.save
        create_message(params[:match][:message], @match)
        @match.broadcast_guide_match
        redirect_to matches_path
      else
        redirect_to new_match_path(location_id: params[:match][:location_id], guide_id: params[:match][:guide_id]), alert: "Request could not be sent, try again later"
      end
    end
  end

  def new
    @location = Location.find(params[:location_id])
    @match = Match.new
    @message = Message.new
  end

  def create_message(message, match)
    @message = Message.new(content: message)
    @message.user = current_user
    @message.match = match
    if @message.save
      flash[:notice] = "message sent to user"
    else
      flash[:notice] = "was not able to send message to user"
    end

  end

  private

  def set_guide
    @guide = User.find(params[:guide_id])
  end

  def set_match
    @match = Match.find(params[:match_id] || params[:id])
  end

  def message_params
    params.require(:message).permit(:content)
  end

  def match_params
    params.require(:match).permit(:guide_id, :location_id)
  end

end

app/views/matches/_guide_match.html.erb
<div id="match_<%= match.id %>">
  <div class="d-flex flex-column border border-3 justify-content-between match-card mb-4">
    <% if incoming %>
      <span class="right status border incoming"><%= incoming %></span>
    <% else %>
      <span class="right status border"><%= match.status %></span>
    <% end %>
    <% if match.tourist.photo.key != nil %>
      <%= cl_image_tag(match.tourist.photo.key, height: 220, width: 372, gravity: "faces", crop: "fill", class: "cloudinary-image") %>
    <% end %>
    <div class="ms-2 mt-1">
      <% if match.status == 'pending' %>
      <h3 class="mt-2"><%= match.tourist.name %> says: </h3>

        <p><%= match.messages.first.content %></p>
        <div class="d-flex">
          <%= button_to 'Accept', match_path(match.id, status: 'accepted'), :method => :patch, class: 'btn btn-outline-primary me-3 mb-2' %>
          <%= button_to 'Decline', match_path(match.id, status: 'declined'), :method => :patch, class: 'btn btn-outline-warning me-3 mb-2' %>
        </div>

      <% elsif match.status == 'accepted' %>
        <h3 class="mt-2"><%= match.tourist.name %></h3>
        <div class="d-flex justify-content-start">
          <%= link_to "Chat", match_path(match), class: "btn btn-outline-primary mb-2" %>
        </div>

      <% elsif match.status == "finishing" %>
        <h3 class="mt-2"><%= match.tourist.name %></h3>

        <div class="d-flex flex-column justify-content-end">
          <p>Did you go on a trip with <%= match.tourist.name %>?</p>
          <div class="d-flex">
            <%= button_to "Yes", end_match_path(match, value: "yes"), class: "btn btn-outline-primary me-3 mb-2" %>
            <%= button_to "No", end_match_path(match, value: 'no'), data: { turbo_confirm: "This match will be set back to accepted, are you sure?" }, class: 'btn btn-outline-primary  me-3 mb-2' %>
          </div>
        </div>

      <% elsif match.status == "finished" %>
        <div class="d-flex flex-column justify-content-end">
          <p>We hope your tour with <%= match.tourist.name %> was amazing!<p>
          <p><%= match.tourist.name %> can now leave a review for you</p>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/matches/_matches_as_guide.html.erb
<div id="incomming_matches">
  <% locals[:matches].each do |match| %>
    <%=render "guide_match", match: match, incoming: false %>
  <% end %>
</div>

app/views/matches/_matches_as_tourist.erb
<h1>Your guides</h1>
<% locals[:matches].each do |match| %>
  <div class="d-flex border w-100 mt-4 rounded justify-content-between">
    <% if match.guide.photo.key != nil %>
      <%= cl_image_tag match.guide.photo.key, width: 300, crop: :fill, class: "justify-content-center my-3" %>
    <% end %>
    <div class="justify-content-start text-start ms-2 mt-1">
      <h2><%= match.guide.name %></h2>
      <p><%= match.guide.guide_description %></p>
      <p>Status: <strong><%= match.status %></strong><%= " - wait for confirmation" if match.status === 'pending' %></p>
      <% if match.status == 'pending' %>
        <p>Waiting for confirmation</p>
      <% else %>
        <%= link_to "Chat", match_path(match), class: "btn btn-primary mb-3" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/matches/_matches_as_tourist.html.erb
<% locals[:matches].each do |match| %>
    <%=render "tourist_match", match: match %>
<% end %>

app/views/matches/_tourist_match.html.erb
<div id="match_<%= match.id %>">
  <div class="d-flex flex-column border border-2 justify-content-between">
    <% if match.guide.photo.key != nil %>
      <a href="users/<%=match.guide.id%>">
        <%= cl_image_tag(match.guide.photo.key, height: 220, width: 372, gravity: "faces", crop: "fill", class: "cloudinary-image") %>
      </a>
    <% end %>
    <div class="text-start ms-2 mt-1">
      <h2> <%= match.guide.name %> </h2>
      <p><%= match.guide.short_description %></p>
      <p>
        <%= "Waiting for confirmation." if match.status === 'pending' %>
        <%= "Waiting for confirmation to write a review." if match.status === 'finishing' %>
        <%= "This connection is declined, you can't send a new request." if match.status === 'declined' %>
      </p>
      <% if match.status == 'accepted' %>

        <div class="d-flex justify-content-start">
          <%= link_to "Chat", match_path(match), class: "btn btn-outline-primary mb-3" %>
          <%= button_to "Finish tour", finish_match_path(match), class: "btn btn-outline-warning ms-3 mb-3" %>
        </div>

      <% elsif match.status == "finished" %>
          <%= button_to "Write review", new_match_review_path(match.id), method: :get, class: "btn btn-outline-primary mb-3" %>
      <% end %>

    </div>
  </div>
</div>

app/views/matches/index.html.erb
<div class="basic-padding">
  <div class="mt-3">
    <% if @matches_as_guide.empty? && @matches_as_tourist.empty? %>
      <h1 class="text-center mb-3">You have no connections</h1>
      <p class="text-center">Start connecting with a guide by looking for them on the map!</p>
    <% end %>

    <%= turbo_stream_from "incomming_matches-#{current_user.id}"%>

    <% if @matches_as_guide.empty? %>
      <%= render "matches_as_guide", locals: { matches: @matches_as_guide } %>
    <% else %>

      <h1>Your tourists</h1>
        <%= render "matches_as_guide", locals: { matches: @matches_as_guide } %>
    <% end %>

    <% if @matches_as_tourist.any? %>
      <br>
      <h1 class="guides-heading">Your guides</h1>
      <div class="location-divider2"></div>
      <%= render "matches_as_tourist", locals: { matches: @matches_as_tourist } %>
    <% end %>
  </div>
</div>

app/views/matches/new.html.erb
<div class="d-flex justify-content-center">
  <% if @guide.photo.key != nil %>
    <%= cl_image_tag @guide.photo.key, height: 250, width: 350, crop: "fill", class: "cloudinary-image" %>
  <% end %>
</div>

<div class="basic-padding mt-3">
  <h1>Send a request to <%= @guide.name %></h1>
  <div class="new-match-form">

    <%= simple_form_for @match do |f| %>
        <%= f.input :guide_id, as: :hidden, input_html: { value: @guide.id } %>
        <%= f.input :location_id, as: :hidden, input_html: { value: @location.id } %>
        <%= f.input :message, as: :text, label: false, input_html: { placeholder: "Introduce yourself...", value: "" } %>
       <%= f.button :submit, value: "Send request", class: 'btn btn-primary'%>
    <% end %>
  </div>

</div>

app/views/matches/show.html.erb
<div class="message-container">

<h3 class="text-center">Chat with <%= @matched_user.name %></h3>
<%= turbo_stream_from "chat-#{@match.id}-#{current_user.id}" %>

  <div id="messages" class="messages">
    <% @match.messages.each do |message| %>
      <%= render "messages/message", message: message, user: current_user %>
    <% end %>
  </div>

<div class="basic-padding">
  <div id="new_message mb-8" class="new-message">
      <%= simple_form_for [@match, @message], html: { class: "message-form", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f| %>
          <section class="d-flex flex-row chat-form">
            <%= f.input :content, label: false, placeholder: "Message #{@matched_user.name}" %>
            <%= f.submit "Send", class: "btn btn-primary" %>
          </section>
      <% end %>
  </div>
</div>
</div>